from setuptools import setup, find_packages

setup(
    name="autoga",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.19.2",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "statsmodels>=0.13.0",
        "scipy>=1.7.0",
        "fancyimpute>=0.7.0",
        "impyute>=0.0.8",
        "jellyfish>=1.1.3",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "joblib>=1.0.0",
        "psutil>=5.8.0",
        "pyyaml>=6.0.0",
        "tqdm>=4.62.0",
        "pandas-profiling>=2.11.0",
        "openml>=0.12.0",
        "xgboost>=1.3.3",
        "lightgbm>=3.0.0",
        "catboost>=0.24.0"
    ],
    python_requires=">=3.9",
)